//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AGCanteenEntities : DbContext
    {
        public DB_AGCanteenEntities()
            : base("name=DB_AGCanteenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Breakfast> Tbl_Breakfast { get; set; }
        public virtual DbSet<Tbl_BreakfastCategory> Tbl_BreakfastCategory { get; set; }
        public virtual DbSet<Tbl_Cake> Tbl_Cake { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<Tbl_Fruit> Tbl_Fruit { get; set; }
        public virtual DbSet<Tbl_Lunch> Tbl_Lunch { get; set; }
        public virtual DbSet<Tbl_Order> Tbl_Order { get; set; }
        public virtual DbSet<Tbl_OrderLine> Tbl_OrderLine { get; set; }
    }
}
