//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cake()
        {
            this.Tbl_OrderLine = new HashSet<Tbl_OrderLine>();
        }
    
        public string Fld_CakeName { get; set; }
        public Nullable<decimal> Fld_CakePrice { get; set; }
        public string Fld_Description { get; set; }
        public decimal Fld_CakeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderLine> Tbl_OrderLine { get; set; }
    }
}
