//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Breakfast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Breakfast()
        {
            this.Tbl_OrderLine = new HashSet<Tbl_OrderLine>();
        }
    
        public string Fld_BreakfastName { get; set; }
        public Nullable<decimal> Fld_BreakfastPrice { get; set; }
        public decimal Fld_BrealfastID { get; set; }
        public Nullable<decimal> Fld_CategoryID { get; set; }
    
        public virtual Tbl_BreakfastCategory Tbl_BreakfastCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderLine> Tbl_OrderLine { get; set; }
    }
}
