//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_WeekOrder
    {
        public Nullable<decimal> Fld_CustomerID { get; set; }
        public Nullable<decimal> Fld_Price { get; set; }
        public Nullable<decimal> Fld_WeekNumber { get; set; }
        public Nullable<decimal> Fld_LunchID { get; set; }
        public Nullable<decimal> Fld_OrderID { get; set; }
        public decimal Fld_WeekOrderID { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual Tbl_Lunch Tbl_Lunch { get; set; }
        public virtual Tbl_Order Tbl_Order { get; set; }
    }
}
