//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderLine
    {
        public Nullable<decimal> Fld_OrderID { get; set; }
        public Nullable<decimal> Fld_FruitID { get; set; }
        public Nullable<decimal> Fld_BreakfastID { get; set; }
        public Nullable<decimal> Fld_LunchID { get; set; }
        public Nullable<decimal> Fld_CakeID { get; set; }
        public decimal Fld_OrderLineID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Tbl_Breakfast Tbl_Breakfast { get; set; }
        public virtual Tbl_Cake Tbl_Cake { get; set; }
        public virtual Tbl_Fruit Tbl_Fruit { get; set; }
        public virtual Tbl_Lunch Tbl_Lunch { get; set; }
        public virtual Tbl_Order Tbl_Order { get; set; }
    }
}
