//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BreakfastCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BreakfastCategory()
        {
            this.Tbl_Breakfast = new HashSet<Tbl_Breakfast>();
        }
    
        public decimal Fld_CategoryID { get; set; }
        public string Fld_CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Breakfast> Tbl_Breakfast { get; set; }
    }
}
